import sys
from Node import Node
from AStarAlgorithm import AStarAlgorithm
from Bfs import Bfs

# Topological sort

# Algoritmo Topological Sort para gráficas acíclicas dirigidas.
# Primero agregamos el vertice actual, a los vértices visitados
# después para todos los vecinos que no se han visitado; si el vecino no está dentro de visitado, lo visitamos 
# entonces, si todos los vecinos ya están visitados, agregamos el vértice actual a orden
# finalmente, si ninguno de los vertices ha sido visitado, seleccionamos uno nuevo para visitar.
# regresamos orden 

aristas = {"a": ["c", "d"], "b": ["e", "c"], "c": ["d"], "d": [], "e": ["a", "c"]}
vertices = ["a", "b", "c", "d", "e"]

def topological_sort(inicio, visitado, orden):
    actual = inicio
    visitado.append(actual)
    vecinos = aristas[actual]
    
    for vecino in vecinos:
        if vecino not in visitado:
            orden = topological_sort(vecino, visitado, orden)  
    orden.append(actual)
    if len(visitado) != len(vertices):
        for vertice in vertices:
            if vertice not in visitado:
                orden = topological_sort(vertice, visitado, orden)
    
    return orden

class Tarea1(object):
    
    def __init__(self):
        
        "linea 1"
        self.observatorio = Node("observatorio", 5960)
        self.tacubaya = Node("tacubaya", 4660)
        self.Juanacatlan = Node("juanacatlan", 3920)
        self.chapultepec = Node("chapultepec", 3650)
        self.sevilla = Node ("sevilla", 3260) 
        self.insurgentes = Node ("insurgentes", 2700)
        self.cuauhtemoc = Node("cuauhtemoc", 2290)
        self.balderas = Node ("balderas", 2210)
        self.saltoDelAgua = Node("saltoDelAgua", 2200)
        self.isabelLaCatolica = Node("isabelLaCatolica", 2230)
        self.pinoSuarez = Node("pinoSuarez", 2360)
        self.merced = Node("merced", 2820)
        self.candelaria = Node("candelaria", 3450)
        self.sanLazaro = Node("sanLazaro", 4200)
        self.moctezuma = Node("moctezuma", 4210)
        self.balbuena = Node("balbuena", 4660)
        self.blvdPuertoAereo = Node("blvdPuertoAereo", 5310)
        self.gomezFarias = Node("gomezFarias", 5770)
        self.zaragoza = Node ("zaragoza", 6460)
        self.pantitlan = Node("pantitlan", 7690)

        self.pantitlan.addChild(self.zaragoza, 1320)
        self.zaragoza.addChild(self.gomezFarias, 762)
        self.gomezFarias.addChild(self.blvdPuertoAereo, 611)
        self.blvdPuertoAereo.addChild(self.balbuena, 595)
        self.balbuena.addChild(self.moctezuma, 703)
        self.moctezuma.addChild(self.sanLazaro, 478)
        self.sanLazaro.addChild(self.candelaria, 866)
        self.candelaria.addChild(self.merced, 698)
        self.merced.addChild(self.pinoSuarez, 745)
        self.pinoSuarez.addChild(self.isabelLaCatolica, 382)
        self.isabelLaCatolica.addChild(self.saltoDelAgua, 445)
        self.saltoDelAgua.addChild(self.balderas, 458)
        self.balderas.addChild(self.cuauhtemoc, 409)
        self.cuauhtemoc.addChild(self.insurgentes, 793)
        self.insurgentes.addChild(self.sevilla, 645)
        self.sevilla.addChild(self.chapultepec, 501)
        self.chapultepec.addChild(self.Juanacatlan, 973)
        self.Juanacatlan.addChild(self.tacubaya, 1158)
        self.tacubaya.addChild(self.observatorio, 1262)

        self.zaragoza.addChild(self.pantitlan, 1320)
        self.gomezFarias.addChild(self.zaragoza, 762)
        self.blvdPuertoAereo.addChild(self.gomezFarias, 611)
        self.balbuena.addChild(self.blvdPuertoAereo, 595)
        self.moctezuma.addChild(self.balbuena, 703)
        self.sanLazaro.addChild(self.moctezuma, 478)
        self.candelaria.addChild(self.sanLazaro, 866)
        self.merced.addChild(self.candelaria, 698)
        self.pinoSuarez.addChild(self.merced, 745)
        self.isabelLaCatolica.addChild(self.pinoSuarez, 382)
        self.saltoDelAgua.addChild(self.isabelLaCatolica, 445)
        self.balderas.addChild(self.saltoDelAgua, 458)
        self.cuauhtemoc.addChild(self.balderas, 409)
        self.insurgentes.addChild(self.cuauhtemoc, 793)
        self.sevilla.addChild(self.insurgentes, 645)
        self.chapultepec.addChild(self.sevilla, 501)
        self.Juanacatlan.addChild(self.chapultepec, 973)
        self.tacubaya.addChild(self.Juanacatlan, 1158)
        self.observatorio.addChild(self.tacubaya, 1262)

        "Linea 2"
        self.cuatroCaminos = Node("cuatroCaminos", 9540)
        self.panteones = Node("panteones", 8410)
        self.tacuba = Node("tacuba", 7370)
        self.cuitlahuac = Node("cuitlahuac", 6770)
        self.popotla = Node("popotla", 6050)
        self.colegioMilitar = Node("colegioMilitar", 5710)
        self.normal = Node("normal", 4770)
        self.sanCosme = Node("sanCosme", 4250)
        self.revolucion = Node("revolucion", 3700)
        self.hidalgo = Node("hidalgo", 3370)
        self.bellasArtes = Node("bellasArtes", 3240)
        self.allende = Node("allende", 3220)
        self.zocalo = Node("zocalo", 3060)
        self.pinoSuarez = Node("pinoSuarez", 2360)
        self.sanAntonioAbad = Node("sanAntonioAbad", 1370)
        self.chabacano = Node("chabacano", 1140)
        self.viaducto = Node("viaducto", 1020)
        self.xola = Node("xola", 1480)
        self.villaDeCortes = Node("villaDeCortes", 2280)
        self.nativitas = Node("nativitas", 3120)
        self.portales = Node("portales", 4130)
        self.ermita = Node("ermita", 5130)
        self.generalAnaya = Node("generalAnaya", 6000)
        self.tasquena = Node("tasquena", 7070)

        self.cuatroCaminos.addChild(self.panteones, 1639)
        self.panteones.addChild(self.tacuba, 1416)
        self.tacuba.addChild(self.cuitlahuac, 637)
        self.cuitlahuac.addChild(self.popotla, 620)
        self.popotla.addChild(self.colegioMilitar, 462)
        self.colegioMilitar.addChild(self.normal, 516)
        self.normal.addChild(self.sanCosme, 657)
        self.sanCosme.addChild(self.revolucion, 537)
        self.revolucion.addChild(self.hidalgo, 587)
        self.hidalgo.addChild(self.bellasArtes, 447)
        self.bellasArtes.addChild(self.allende, 387)
        self.allende.addChild(self.zocalo, 602)
        self.zocalo.addChild(self.pinoSuarez, 745)
        self.pinoSuarez.addChild(self.sanAntonioAbad, 817)
        self.sanAntonioAbad.addChild(self.chabacano, 642)
        self.chabacano.addChild(self.viaducto, 774)
        self.viaducto.addChild(self.xola, 490)
        self.xola.addChild(self.villaDeCortes, 698)
        self.villaDeCortes.addChild(self.nativitas, 750)
        self.nativitas.addChild(self.portales, 924)
        self.portales.addChild(self.ermita, 748)
        self.ermita.addChild(self.generalAnaya, 838)
        self.generalAnaya.addChild(self.tasquena, 1330)

        self.panteones.addChild(self.cuatroCaminos, 1639)
        self.tacuba.addChild(self.panteones, 1416)
        self.cuitlahuac.addChild(self.tacuba, 637)
        self.popotla.addChild(self.cuitlahuac, 620)
        self.colegioMilitar.addChild(self.popotla, 462)
        self.normal.addChild(self.colegioMilitar, 516)
        self.sanCosme.addChild(self.normal, 657)
        self.revolucion.addChild(self.sanCosme, 537)
        self.hidalgo.addChild(self.revolucion, 587)
        self.bellasArtes.addChild(self.hidalgo, 447)
        self.allende.addChild(self.bellasArtes, 387)
        self.zocalo.addChild(self.allende, 602)
        self.pinoSuarez.addChild(self.zocalo, 745)
        self.sanAntonioAbad.addChild(self.pinoSuarez, 817)
        self.chabacano.addChild(self.sanAntonioAbad, 642)
        self.viaducto.addChild(self.chabacano, 774)
        self.xola.addChild(self.viaducto, 490)
        self.villaDeCortes.addChild(self.xola, 698)
        self.nativitas.addChild(self.villaDeCortes, 750)
        self.portales.addChild(self.nativitas, 924)
        self.ermita.addChild(self.portales, 748)
        self.generalAnaya.addChild(self.ermita, 838)
        self.tasquena.addChild(self.generalAnaya, 1330)

        "Linea 3"
        self.indiosVerdes = Node("indiosVerdes", 9900)
        self.deportivo18DeMarzo = Node("deportivo18DeMarzo", 8870)
        self.potrero = Node("potrero", 7870)
        self.laRaza = Node("laRaza", 6980)
        self.tlatelolco = Node("tlatelolco", 5420)
        self.guerrero = Node("guerrero", 4240)
        self.hidalgo = Node("hidalgo", 3370)
        self.juarez = Node("juarez", 2920)
        self.balderas = Node("balderas", 2210)
        self.ninosHeroes = Node("ninosHeroes", 1460)
        self.hospitalGeneral = Node("hospitalGeneral", 1200)
        self.centroMedico = Node("centroMedico", 1170)
        self.etiopia = Node("etiopia", 1790)
        self.eugenia = Node("eugenia", 2710)
        self.divisionDelNorte = Node("divisionDelNorte", 3530)
        self.zapata = Node("zapata", 4540)
        self.coyoacan = Node("coyoacan", 5820)
        self.viveros = Node("viveros", 6780)
        self.miguelADeQuevedo = Node("miguelADeQuevedo", 7790)
        self.copilco = Node("copilco", 8630)
        self.universidad = Node("universidad", 9720)
        

        self.indiosVerdes.addChild(self.deportivo18DeMarzo, 1166)
        self.deportivo18DeMarzo.addChild(self.potrero, 966)
        self.potrero.addChild(self.laRaza, 1106)
        self.laRaza.addChild(self.tlatelolco, 1445)
        self.tlatelolco.addChild(self.guerrero, 1042)
        self.guerrero.addChild(self.hidalgo, 702)
        self.hidalgo.addChild(self.juarez, 251)
        self.juarez.addChild(self.balderas, 659)
        self.balderas.addChild(self.ninosHeroes, 665)
        self.ninosHeroes.addChild(self.hospitalGeneral, 559)
        self.hospitalGeneral.addChild(self.centroMedico, 653)
        self.centroMedico.addChild(self.etiopia, 1119)
        self.etiopia.addChild(self.eugenia, 950)
        self.eugenia.addChild(self.divisionDelNorte, 715)
        self.divisionDelNorte.addChild(self.zapata, 794)
        self.zapata.addChild(self.coyoacan, 1153)
        self.coyoacan.addChild(self.viveros, 908)
        self.viveros.addChild(self.miguelADeQuevedo, 824)
        self.miguelADeQuevedo.addChild(self.copilco, 1295)
        self.copilco.addChild(self.universidad, 1306)

        self.deportivo18DeMarzo.addChild(self.indiosVerdes, 1166)
        self.potrero.addChild(self.deportivo18DeMarzo, 966)
        self.laRaza.addChild(self.potrero, 1106)
        self.tlatelolco.addChild(self.laRaza, 1445)
        self.guerrero.addChild(self.tlatelolco, 1042)
        self.hidalgo.addChild(self.guerrero, 702)
        self.juarez.addChild(self.hidalgo, 251)
        self.balderas.addChild(self.juarez, 659)
        self.ninosHeroes.addChild(self.balderas, 665)
        self.hospitalGeneral.addChild(self.ninosHeroes, 559)
        self.centroMedico.addChild(self.hospitalGeneral, 653)
        self.etiopia.addChild(self.centroMedico, 1119)
        self.eugenia.addChild(self.etiopia, 950)
        self.divisionDelNorte.addChild(self.eugenia, 715)
        self.zapata.addChild(self.divisionDelNorte, 794)
        self.coyoacan.addChild(self.zapata, 1153)
        self.viveros.addChild(self.coyoacan, 908)
        self.miguelADeQuevedo.addChild(self.viveros, 824)
        self.copilco.addChild(self.miguelADeQuevedo, 1295)
        self.universidad.addChild(self.copilco, 1306)
        
        "Linea 9"
        self.tacubaya = Node("tacubaya", 4660)
        self.patriotismo = Node("patriotismo", 3600)
        self.chilpancingo = Node("chilpancingo", 2630)
        """self.centroMedico = Node("centroMedico", 1170)"""
        self.lazaroCardenas = Node("lazaroCardenas", 0)
        self.chabacano = Node("chabacano", 1140)
        self.jamaica = Node("jamaica", 2370)
        self.mixiuhca = Node("mixiuhca", 3280)
        self.velodromo = Node("velodromo", 4140)
        self.ciudadDeportiva = Node("ciudadDeportiva", 5540)
        self.puebla = Node("puebla", 6460)
        self.pantitlan = Node("pantitlan", 7690)

        self.tacubaya.addChild(self.patriotismo, 1133)
        self.patriotismo.addChild(self.chilpancingo, 955)
        self.chilpancingo.addChild(self.centroMedico, 1152)
        self.centroMedico.addChild(self.lazaroCardenas, 1059)
        self.lazaroCardenas.addChild(self.chabacano, 1000)
        self.chabacano.addChild(self.jamaica, 1031)
        self.jamaica.addChild(self.mixiuhca, 942)
        self.mixiuhca.addChild(self.velodromo, 821)
        self.velodromo.addChild(self.ciudadDeportiva, 1110)
        self.ciudadDeportiva.addChild(self.puebla, 800)
        self.puebla.addChild(self.pantitlan, 1380)
        
        self.patriotismo.addChild(self.tacubaya, 1133)
        self.chilpancingo.addChild(self.patriotismo, 955)
        self.centroMedico.addChild(self.chilpancingo, 1152)
        self.lazaroCardenas.addChild(self.centroMedico, 1059)
        self.chabacano.addChild(self.lazaroCardenas, 1000)
        self.jamaica.addChild(self.chabacano, 1031)
        self.mixiuhca.addChild(self.jamaica, 942)
        self.velodromo.addChild(self.mixiuhca, 821)
        self.ciudadDeportiva.addChild(self.velodromo, 1110)
        self.puebla.addChild(self.ciudadDeportiva, 800)
        self.pantitlan.addChild(self.puebla, 1380)

        "Linea 12"
        self.tlahuac = Node("tlahuac", 19130)
        self.tlaltenco = Node("tlaltenco", 17790)
        self.zapotitlan = Node("zapotitlan", 16830)
        self.nopalera = Node("nopalera", 15720)
        self.olivos = Node("olivos", 14530)
        self.tezonco = Node("tezonco", 13960)
        self.perifericoOriente = Node("perifericoOriente", 12390)
        self.calle11 = Node("calle11", 11410)
        self.lomasEstrella = Node("lomasEstrella", 10730)
        self.sanAndresTomatlan = Node("sanAndresTomatlan", 9740)
        self.culhuacan = Node("culhuacan", 8660)
        self.atlalilco = Node("atlalilco", 7300)
        self.mexicaltzingo = Node("mexicaltzingo", 5930)
        self.ermita = Node("ermita", 5130)
        self.ejeCentral = Node("ejeCentral", 5180)
        self.parqueDeLosVenados = Node("parqueDeLosVenados", 4340)
        """self.zapata = Node("zapata", 4540)"""
        self.hospital20DeNoviembre = Node("hospital20DeNoviembre", 4820)
        self.insurgentesSur = Node("insurgentesSur", 5210)
        self.mixcoac = Node("mixcoac", 5740)
        
        self.tlahuac.addChild(self.tlaltenco, 1298)
        self.tlaltenco.addChild(self.zapotitlan, 1115)
        self.zapotitlan.addChild(self.nopalera, 1276)
        self.nopalera.addChild(self.olivos, 1360)
        self.olivos.addChild(self.tezonco, 490)
        self.tezonco.addChild(self.perifericoOriente, 1545)
        self.perifericoOriente.addChild(self.calle11, 1111)
        self.calle11.addChild(self.lomasEstrella, 906)
        self.lomasEstrella.addChild(self.sanAndresTomatlan, 1060)
        self.sanAndresTomatlan.addChild(self.culhuacan, 990)
        self.culhuacan.addChild(self.atlalilco, 1671)
        self.atlalilco.addChild(self.mexicaltzingo, 1922)
        self.mexicaltzingo.addChild(self.ermita, 1805)
        self.ermita.addChild(self.ejeCentral, 895)
        self.ejeCentral.addChild(self.parqueDeLosVenados, 1280)
        self.parqueDeLosVenados.addChild(self.zapata, 563)
        self.zapata.addChild(self.hospital20DeNoviembre, 450)
        self.hospital20DeNoviembre.addChild(self.insurgentesSur, 725)
        self.insurgentesSur.addChild(self.mixcoac, 651)
        
        self.tlaltenco.addChild(self.tlahuac, 1298)
        self.zapotitlan.addChild(self.tlaltenco, 1115)
        self.nopalera.addChild(self.zapotitlan, 1276)
        self.olivos.addChild(self.nopalera, 1360)
        self.tezonco.addChild(self.olivos, 490)
        self.perifericoOriente.addChild(self.tezonco, 1545)
        self.calle11.addChild(self.perifericoOriente, 1111)
        self.lomasEstrella.addChild(self.calle11, 906)
        self.sanAndresTomatlan.addChild(self.lomasEstrella, 1060)
        self.culhuacan.addChild(self.sanAndresTomatlan, 990)
        self.atlalilco.addChild(self.culhuacan, 1671)
        self.mexicaltzingo.addChild(self.atlalilco, 1922)
        self.ermita.addChild(self.mexicaltzingo, 1805)
        self.ejeCentral.addChild(self.ermita, 895)
        self.parqueDeLosVenados.addChild(self.ejeCentral, 1280)
        self.zapata.addChild(self.parqueDeLosVenados, 563)
        self.hospital20DeNoviembre.addChild(self.zapata, 450)
        self.insurgentesSur.addChild(self.hospital20DeNoviembre, 725)
        self.mixcoac.addChild(self.insurgentesSur, 651)

    def searchAStarAlgorithm(self):
        print("\nBuscando ruta optima con Algoritmo A*")
        astar = AStarAlgorithm(self.coyoacan, self.lazaroCardenas)
        print("Nodo Inicial: %s -----> Nodo Final %s" % (self.coyoacan.name, self.lazaroCardenas.name))
        astar.run()

    def searchBfs(self):
        print("\nBuscando ruta optima con Algoritmo Bfs*")
        bfs = Bfs(self.coyoacan, self.lazaroCardenas)
        print("Nodo Inicial: %s -----> Nodo Final %s" % (self.coyoacan.name, self.lazaroCardenas.name))
        bfs.run()

if __name__ == "__main__":
    orden = topological_sort("a", [], [])
    print(orden)
    
    try:
        Tarea1 = Tarea1()
        Tarea1.searchBfs()
        Tarea1.searchAStarAlgorithm()
    except (ValueError, FileNotFoundError, AttributeError) as ex:
        print(ex)